// backend/insertProducts.js
import mongoose from 'mongoose';
import Product from './models/Product.js';
import dotenv from 'dotenv';

dotenv.config();

const MONGO_URI = process.env.MONGODB_URI;

if (!MONGO_URI) {
  console.error('MONGO_URI is not defined');
  process.exit(1);
}

mongoose.connect(MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
.then(async () => {
  console.log('Connected to MongoDB');
  const products = [
    {
      name: "Tesla Model S",
      year: "2022",
      brand: "Tesla",
      logo: "https://www.freepnglogos.com/uploads/tesla-logo-png-13.png",
      images: ['https://static-assets.tesla.com/configurator/compositor?context=design_studio_2?&bkba_opt=1&view=STUD_3QTR_V2&size=1400&model=ms&options=$MDLS,$MTS03,$PPSW,$RFFR,$WTD2,$INFTP,$PI01,$APBS,$SC04,$CPF0&crop=1400,850,300,130&',
              'https://assets.zappyride.com/img/vehicles/chromestyle/412485/style-set-1280/2020TSC020019_1280_03.png',
              'https://cdn.motor1.com/images/mgl/yEB3G/s3/2021-tesla-model-s.webp'],
      fuel: "Electric",
      seats: "Five Seaters",
      topSpeed: "322 km/h",
      engine: "Electric",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 4500,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Porsche 911",
      year: "2019",
      brand: "Porsche",
      logo: "https://pngimg.com/uploads/porsche_logo/porsche_logo_PNG7.png",
      images: ['https://pictures.porsche.com/rtt/iris?COSY-EU-100-1711coMvsi60AAt5FwcmBEgA4qP8iBUDxPE3Cb9pNXkBuNYdMGF4tl3U0%25z8rMHIspMBvMZq6G5OtgSv31nBJaA4qh4NSEGkaW%25cz91wxuzbUUdMGLqk0D3LF%25vUqbxAuWXsOaUJeV6iTrd2zhRc2cUWqA7fQhdiOJUPYyMN9nReCkxo4y7zInhF%25vUqYHPuWXsO5XJeV6iTJ83zhp4NdTxf4KxJhvaBH6mOcuLAlWRDdV2DU',
              'https://pictures.porsche.com/rtt/iris?COSY-EU-100-1711coMvsi60AAt5FwcmBEgA4qP8iBUDxPE3Cb9pNXkBuNYdMGF4tl3U0%25z8rMH1spMBvMZq6G5OtgSv31nBJaA4qh4NSEGkaW%25cz91wxuzbUUdMGLqk0D3LF%25vUqbxAuWXsOaUJeV6iTrd2zhRc2cUWqA7fQhdiOJUPYyMN9nReCkxo4y7zInhF%25vUqYHPuWXsO5XJeV6iTJ83zhp4NdTxf4KxJhvaBH6mOcuLAlWRDdV2DU',
              'https://pictures.porsche.com/rtt/iris?COSY-EU-100-1711coMvsi60AAt5FwcmBEgA4qP8iBUDxPE3Cb9pNXkBuNYdMGF4tl3U0%25z8rMH8spMBvMZq6G5OtgSv31nBJaA4qh4NSEGkaW%25cz91wxuzbUUdMGLqk0D3LF%25vUqbxAuWXsOaUJeV6iTrd2zhRc2cUWqA7fQhdiOJUPYyMN9nReCkxo4y7zInhF%25vUqYHPuWXsO5XJeV6iTJ83zhp4NdTxf4KxJhvaBH6mOcuLAlWRDdV2DU'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "310 km/h",
      engine: "3.0-liter H6",
      transmission: "Manual",
      airConditioning: "Yes",
      price: 3800,
      location: "Pretoria",
      category: "Popular"
    },
    {
      name: "Lamborghini Aventador",
      year: "2020",
      brand: "Lamborghini",
      logo: 'https://www.freepnglogos.com/uploads/lamborghini-logo-png/lamborghini-logo-gallery-italian-car-logos-0.png',
      images: ['https://www.motortrend.com/uploads/sites/5/2021/07/Lamborghini-Aventador-LP-780-4-Ultimate-17.jpg?w=768&width=768&q=75&format=webp',
        'https://exoticcars.ae/uploads/cars/lamborghini-aventador-svj/image-1352075.jpg',
        'https://images.caradisiac.com/images/0/9/3/3/190933/S0-lamborghini-aventador-lp-780-4-ultimae-la-fin-d-une-epoque-683506.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "350 km/h",
      engine: "6.5-liter V12",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 5500,
      location: "Pretoria",
      category: "Sports"
    },
    {
      name: "Ford Mustang",
      year: "2020",
      brand: "Ford",
      logo: "https://seeklogo.com/images/F/ford-mustang-logo-A837CDD225-seeklogo.com.png",
      images: ['https://www.ford.co.za/content/dam/Ford/website-assets/latam/za/buildprice/new_mustang_2019_FAF/5-0-gt-series-10at-fastback-FAF/carousel/exterior/17_Oxford_White-billboard.jpg',
        'https://www.westcoastexoticcars.com/imagetag/2054/6/l/Used-2020-Ford-Mustang-Shelby-GT350R-1711747085.jpg',
        'https://www.mustang6g.com/forums/attachments/2020-gt500-base-white-rear-dr-side-png.394205/'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "250 km/h",
      engine: "5.0-liter V8",
      transmission: "Manual",
      airConditioning: "Yes",
      price: 3200,
      location: "Pretoria",
      category: "SUV"
    },
    {
      name: "Audi R8",
      year: "2018",
      brand: "Audi",
      logo: "https://www.freepnglogos.com/uploads/audi-logo-2.png",
      images: ['https://i.pinimg.com/originals/52/47/0c/52470c16e377856cb88ebc48d4e728fb.jpg',
        'https://www.hdcarwallpapers.com/walls/audi_r8_v10_2-wide.jpg',
        'https://images.caricos.com/a/audi/2018_audi_r8_rws/images/1920x1080/2018_audi_r8_rws_61_1920x1080.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "330 km/h",
      engine: "5.2-liter V10",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 6000,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "BMW M3",
      year: "2020",
      brand: "BMW",
      logo: "https://www.freepnglogos.com/uploads/bmw-logo-14.png",
      images: ['https://prod.cosy.bmw.cloud/bmwweb/cosySec?COSY-EU-100-733156fayVOhiL0onTdzmlD9Uwmu1R7Gq3A89RIhNQSht8iAm2YInwlQaGcpRBhS9Q0KE0pODR5YgMYFZP5mlDnEfbc1KVZiNV89RpyeYXUrO6JQToGwgFMA8NFCE%25rrxltjix2xdxgaw178ziwMtECUkwRS7slGAlnbCrXpFhrGlZQ6KjA0XRaYWY4AQ5nmPml0agOybyXQnvIT9PvrO2B3ibHvIjedw9C2BDMzti08eqhk7wD5MLoACt%25whJHFl7f6ou%25KXC1ZHSfWQvrE%25V1Pa2l4fNEbnjhL10s9ODoZE4riIqp3scZwBEvmrxRtesfVZ857Mr1xRUgChZU05GvloRGEgp2XH51wv6jQ%25gx22YDafv0Zjmqn12WFDyLOEjPpqTJIsDVvL3uBrqULJdSeZfdmuzVMR1xdSkNh5E24VA0ogsPoNF4Hvrb10Kc%252Z9K4WxfjRNacP81D501xbUEqg4k89GsLmSKUiprJyz9Gw6ZuTlcptYRS3Xh67m5VdQHYCygNzfimlTv0k1EyX324AYyTQdjcFAq3azDxKo1dnkq8WwHzOALUPKckIFJGb%25JABKup%258QFeWS6fUKKMPVY1nnWhbNmE2PPo90y9Y6bHi4TidR9%25wc3wzSiftxdt7gw178z7fLtECUkC1t7slGAl2nCrXpFRO9lZQ6K5JiXRaYWg2BQ5nHnzQhw8rtK4ew1pidlwPtUDYkxbZLId4ozTQLdecX83D%25hr49GwgiEPyTpRBYnHg0KExhaVGh%25Ww8jSz3ahpD35GaUujDqgXAE7xqNQITkHNeqKrPpw56swT7OY9',
        'https://g80.bimmerpost.com/forums/attachment.php?attachmentid=2443898&stc=1&d=1603386485',
        'https://car-images.bauersecure.com/pagefiles/97739/12bmwm3.jpg'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "290 km/h",
      engine: "3.0-liter I6",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 4500,
      location: "Pretoria",
      category: "Popular"
    },
    {
      name: "Mercedes-Benz G-Class",
      year: "2021",
      brand: "Mercedes",
      logo: "https://www.freepnglogos.com/uploads/mercedes-logo-png/mercedes-logo-mercedes-benz-logo-png-transparent-svg-vector-bie-13.png",
      images: ['https://content.homenetiol.com/2000292/2143540/0x0/4930f7ec95684fc38f09e4a17278957a.jpg',
        'https://klassen.de/media/images/armored/g/armor_g-class_clear.png',
        'https://www.gts-models.com/wp-content/uploads/2023/03/1-18-mercedes-benz-g-63-amg-edition-55-white-2022-05.jpg'],
      fuel: "Petrol",
      seats: "Five Seaters",
      topSpeed: "210 km/h",
      engine: "4.0-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 8000,
      location: "Pretoria",
      category: "SUV"
    },
    {
      name: "Chevrolet Camaro",
      year: "2019",
      brand: "Chevrolet",
      logo: "https://www.pngall.com/wp-content/uploads/13/Chevrolet-Logo-PNG-Cutout.png",
      images: ['https://cgi.chevrolet.com/mmgprod-us/dynres/prove/image.gen?i=2024/1AG37/1AG37__1LT/GAZ_H1T_0ST_1LT_1NF_1SZ_2NF_2ST_4AA_5A7_6X1_7X1_8DX_9DX_9L3_A50_A9B_AKQ_AL0_AM7_AT8_ATH_AV3_AXJ_AYG_B34_BTV_C68_CF5_D31_D80_DG7_EF7_F_FE2_FE9_FJW_HRE_IOR_J24_J71_JL9_KB7_KRV_KTI_LAL_LGX_M97_MAH_MI1_MX0_N10_NE8_NP5_NTB_NV9_PPW_PRF_R0H_R8J_R9N_REG_SBF_SLM_T4L_T61_TDM_U2K_U77_U80_UDD_UE1_UJM_UMN_UPG_UQ3_UST_UVB_V8D_VRG_VRH_VRJ_VRK_VRL_VRM_VRN_VRR_VT7_VV4_VY7_WMY_XL8gmds10.jpg&v=deg01&std=true&country=US&removeCat=&transparentBackgroundPng=true',
        'https://cgi.chevrolet.com/mmgprod-us/dynres/prove/image.gen?i=2024/1AG37/1AG37__1LT/GAZ_H1T_0ST_1LT_1NF_1SZ_2NF_2ST_4AA_5A7_6X1_7X1_8DX_9DX_9L3_A50_A9B_AKQ_AL0_AM7_AT8_ATH_AV3_AXJ_AYG_B34_BTV_C68_CF5_D31_D80_DG7_EF7_F_FE2_FE9_FJW_HRE_IOR_J24_J71_JL9_KB7_KRV_KTI_LAL_LGX_M97_MAH_MI1_MX0_N10_NE8_NP5_NTB_NV9_PPW_PRF_R0H_R8J_R9N_REG_SBF_SLM_T4L_T61_TDM_U2K_U77_U80_UDD_UE1_UJM_UMN_UPG_UQ3_UST_UVB_V8D_VRG_VRH_VRJ_VRK_VRL_VRM_VRN_VRR_VT7_VV4_VY7_WMY_XL8gmds10.jpg&v=deg04&std=true&country=US&removeCat=&transparentBackgroundPng=true',
        'https://cgi.chevrolet.com/mmgprod-us/dynres/prove/image.gen?i=2024/1AG37/1AG37__1LT/GAZ_H1T_0ST_1LT_1NF_1SZ_2NF_2ST_4AA_5A7_6X1_7X1_8DX_9DX_9L3_A50_A9B_AKQ_AL0_AM7_AT8_ATH_AV3_AXJ_AYG_B34_BTV_C68_CF5_D31_D80_DG7_EF7_F_FE2_FE9_FJW_HRE_IOR_J24_J71_JL9_KB7_KRV_KTI_LAL_LGX_M97_MAH_MI1_MX0_N10_NE8_NP5_NTB_NV9_PPW_PRF_R0H_R8J_R9N_REG_SBF_SLM_T4L_T61_TDM_U2K_U77_U80_UDD_UE1_UJM_UMN_UPG_UQ3_UST_UVB_V8D_VRG_VRH_VRJ_VRK_VRL_VRM_VRN_VRR_VT7_VV4_VY7_WMY_XL8gmds10.jpg&v=deg03&std=true&country=US&removeCat=&transparentBackgroundPng=true'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "250 km/h",
      engine: "6.2-liter V8",
      transmission: "Manual",
      airConditioning: "Yes",
      price: 3200,
      location: "Pretoria",
      category: "Sports"
    },
    {
      name: "Ferrari F8",
      year: "2021",
      brand: "Ferrari",
      logo: "https://www.pngall.com/wp-content/uploads/13/Ferrari-Logo.png",
      images: ['https://cdn.motor1.com/images/mgl/nE4wE/s1/ferrari-f8-tributo.jpg',
        'https://cdn.motor1.com/images/mgl/LEgbl/s1/ferrari-f8-tributo.jpg',
        'https://cdn.motor1.com/images/mgl/qjRP1/s1/ferrari-f8-tributo.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "340 km/h",
      engine: "3.9-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 7500,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Lexus RX 350",
      year: "2020",
      brand: "Lexus",
      logo: "https://www.pngall.com/wp-content/uploads/12/Lexus-Logo-PNG-Image.png",
      images: ['https://www.lexus.com/content/dam/lexus/images/models/rx/2024/visualizer/350/exterior/19-inch-five-spoke-alloy-wheels/eminent-white-pearl/large-1.jpg',
        'https://www.lexus.com/content/dam/lexus/images/models/rx/2024/visualizer/350/exterior/19-inch-five-spoke-alloy-wheels/eminent-white-pearl/large-2.jpg',
        'https://www.lexus.com/content/dam/lexus/images/models/rx/2024/visualizer/350/exterior/19-inch-five-spoke-alloy-wheels/eminent-white-pearl/large-3.jpg'],
      fuel: "Petrol",
      seats: "Five Seaters",
      topSpeed: "200 km/h",
      engine: "3.5-liter V6",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 3500,
      location: "Pretoria",
      category: "SUV"
    },
    {
      name: "Bentley Bentayga",
      year: "2021",
      brand: "Bentley",
      logo: "https://www.pngall.com/wp-content/uploads/2016/06/Bentley-PNG-HD.png",
      images: ['https://johannesburg.bentleymotors.com/picserver1/userdata/1/31596/3FAdVwEMPE/01%20bentayga%20base_24my%20-%20front%2034_v4%201400x700.jpg',
        'https://lugano.bentleymotors.com/picserver1/userdata/1/31595/3FAdVwEMPE/side%20profile%201400x700.jpg',
        'https://johannesburg.bentleymotors.com/picserver1/userdata/1/31596/3FAdVwEMPE/02%20bentayga%20base_24my%20-%20rear%2034_v1%201400x700.jpg'],
      fuel: "Petrol",
      seats: "Five Seaters",
      topSpeed: "300 km/h",
      engine: "6.0-liter W12",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 12000,
      location: "Pretoria",
      category: "Popular"
    },
    {
      name: "Nissan GT-R",
      year: "2021",
      brand: "Nissan",
      logo: "https://www.freepnglogos.com/uploads/nissan-logo-23.png",
      images: ['https://edgecast-img.yahoo.net/mysterio/api/969693C886956B2C67B9603D00618CE544E2F4D1F9AB1834FA7B714C5C2A8D07/autoblog/resizefill_w1200_h675;quality_80;format_webp;cc_31536000;/https://s.aolcdn.com/commerce/autodata/images/USD00NIC131C021001.jpg',
        'https://edgecast-img.yahoo.net/mysterio/api/742B63879AEFE0AC709C17B4D046B4E4A5BB9FA0AB6C124B629180F2D4A4EB16/autoblog/resizefill_w1200_h675;quality_80;format_webp;cc_31536000;/https://s.aolcdn.com/commerce/autodata/images/USD00NIC131C021003.jpg',
        'https://edgecast-img.yahoo.net/mysterio/api/05650A6A717C4AE9634D41B158C7A56DC232E1F8A16F819A165A075BEB4143CA/autoblog/resizefill_w1200_h675;quality_80;format_webp;cc_31536000;/https://s.aolcdn.com/commerce/autodata/images/USD00NIC131C021002.jpg'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "330 km/h",
      engine: "3.8-liter V6",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 6500,
      location: "Pretoria",
      category: "Sports"
    },
    {
      name: "Jaguar F-Type",
      year: "2019",
      brand: "Jaguar",
      logo: "https://purepng.com/public/uploads/thumbnail//purepng.com-jaguar-car-logologocar-brand-logoscarsjaguar-car-logo-1701527428194lxija.png",
      images: ['https://topauto.co.za/wp-content/uploads/2022/10/2023-Jaguar-F-Type-header-1-1024x625.jpg',
        'https://topauto.co.za/wp-content/uploads/2022/10/2023-Jaguar-F-Type-1-1024x625.jpg',
        'https://topauto.co.za/wp-content/uploads/2022/10/2023-Jaguar-F-Type-2-1024x625.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "300 km/h",
      engine: "5.0-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 4100,
      location: "Pretoria",
      category: "Popular"
    },
    {
      name: "Bentley Continental GT",
      year: "2020",
      brand: "Bentley",
      logo: "https://www.pngall.com/wp-content/uploads/2016/06/Bentley-PNG-HD.png",
      images: ['https://www.exclusiveautomotivegroup.com/imagetag/3869/main/l/New-2023-Bentley-Continental-GT-Speed-1701901600.jpg',
        'https://johannesburg.bentleymotors.com/picserver1/userdata/1/31596/3FAdVwEMPE/05-634_speed_profile_final_24.jpg',
        'https://johannesburg.bentleymotors.com/picserver1/userdata/1/31596/3FAdVwEMPE/01-1400x700_gt_speed_rear_3_4_final_24.jpg'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "318 km/h",
      engine: "6.0-liter W12",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 6000,
      location: "Pretoria",
      category: "SUV"
    },
    {
      name: "Aston Martin DB11",
      year: "2019",
      brand: "Aston",
      logo: "https://pngimg.com/d/aston_martin_PNG35.png",
      images: ['https://www.topgear.com/sites/default/files/news-listicle/image/2016/02/aston_martin_db11_embargo_010316_1400cet_16.jpg',
        'https://www.topgear.com/sites/default/files/images/cars-road-test/carousel/2018/03/a901d346bbb845d30777f246c821124b/aston_martin_db11_v8_r_max_earey_7.jpg',
        'https://car-images.bauersecure.com/wp-images/974/aston_01.jpg'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "322 km/h",
      engine: "5.2-liter V12",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 5000,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Rolls-Royce Ghost",
      year: "2020",
      brand: "Rolls-Royce",
      logo: "https://pngimg.com/d/rolls_royce_PNG27.png",
      images: ['https://www.zero2turbo.com/wp-content/uploads/2020/09/2021-rolls-royce-ghost-front.jpg',
        'https://www.phantomhire.com/wp-content/uploads/2023/06/ghost_white_lateral-1920x1085.jpg',
        'https://www.cnet.com/a/img/resize/8414c0a1b4db4536523807359c9dfe1fefba27bc/hub/2020/08/30/051d68f5-b182-4abe-82ad-0190bf928e55/rolls-royce-ghost-008.jpg?auto=webp&width=1200'],
      fuel: "Petrol",
      seats: "Five Seaters",
      topSpeed: "250 km/h",
      engine: "6.6-liter V12",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 7500,
      location: "Pretoria",
      category: "Popular"
    },
    {
      name: "Bugatti Chiron",
      year: "2021",
      brand: "Bugatti",
      logo: "https://pngimg.com/d/bugatti_logo_PNG12.png",
      images: ['https://car-images.bauersecure.com/wp-images/3378/voiture_noire_052.jpg',
        'https://car-images.bauersecure.com/wp-images/3378/voiture_noire_050.jpg',
        'https://hips.hearstapps.com/hmg-prod/images/02-auslieferungen-2017-bugatti-1513865133.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "420 km/h",
      engine: "8.0-liter W16",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 12000,
      location: "Pretoria",
      category: "Sports"
    },
    {
      name: "Aston Martin Vantage",
      year: "2020",
      brand: "Aston",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://images-stag.jazelc.com/uploads/theautopian-m2en/Aston-Martin-Vantage_02.jpg',
        'https://www.autocar.co.uk/sites/autocar.co.uk/files/images/car-reviews/first-drives/legacy/aston-martin-vantage-side-autocar.jpg',
        'https://www.autocar.co.uk/sites/autocar.co.uk/files/images/car-reviews/first-drives/legacy/aston-martin-vantage-rear-quarter-autocar.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "314 km/h",
      engine: "4.0-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 4800,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Alfa Romeo Giulia",
      year: "2019",
      brand: "Alfa",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://car-images.bauersecure.com/wp-images/11324/0000001alfagiulia.jpg',
        'https://www.topgear.com/sites/default/files/cars-car/image/2023/05/1-Alfa-Romeo-Giulia.jpg?w=1280&h=720',
        'https://medias.fcacanada.ca//specs/alfaromeo/giulia/year-2023/media/images/mozaic/2023-alfa-romeo-giulia-design-mosaic-06-rear-sport-diffuser_3a99b370a7d2c75b45cf10865591f657-2000x1000.png'],
      fuel: "Petrol",
      seats: "Five Seaters",
      topSpeed: "307 km/h",
      engine: "2.9-liter V6",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 3000,
      location: "Pretoria",
      category: "Popular"
    },
    {
      name: "Maserati Ghibli",
      year: "2019",
      brand: "Maserati",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://vehicle-images.dealerinspire.com/28e3-110008660/ZAM57YTM4RX451091/63936edbe07c95354330e3b33185b74e.jpg',
        'https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/13q2/510830/2014-maserati-ghibli-photos-and-info-news-car-and-driver-photo-511417-s-original.jpg',
        'https://gs-exclusive.com/media/pages/maserati-ghibli-evo/slideshow/3055899827-1701273465/maserati-ghibli-evo-slide-02.jpg'],
      fuel: "Petrol",
      seats: "Five Seaters",
      topSpeed: "285 km/h",
      engine: "3.0-liter V6",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 3700,
      location: "Cape Town",
      category: "SUV"
    },
    {
      name: "Lexus LC 500",
      year: "2020",
      brand: "Lexus",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://lexuscdn.rotorint.com/LC/2023_05_May/001/e/360/png/lo/1200x675/SPN_LLC_010083LA202A14130A0_comp_000.png',
        'https://www.lexus.co.za/_next/image?url=https%3A%2F%2Flexuslife.co.za%2Fwp-content%2Fuploads%2F2024%2F02%2FLexus_LC500_slider_1440x600_4r.jpg&w=1920&q=100',
        'https://www.vegasautogallery.com/imagetag/1856/10/l/Used-2021-Lexus-LC-500-1662830434.jpg'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "270 km/h",
      engine: "5.0-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 4200,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Pagani Huayra",
      year: "2018",
      brand: "Pagani",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://static1.hotcarsimages.com/wordpress/wp-content/uploads/2022/04/2021-Pagani-Imola.jpg',
        'https://en.wheelz.me/wp-content/uploads/2024/02/Huayra-R-Evo-01-Laterale.webp',
        'https://static0.carbuzzimages.com/wordpress/wp-content/uploads/gallery-images/original/1228000/0/1228087.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "383 km/h",
      engine: "6.0-liter V12",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 15000,
      location: "Pretoria",
      category: "Sports"
    },
    {
      name: "Koenigsegg Jesko",
      year: "2021",
      brand: "Koenigsegg",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://car-images.bauersecure.com/wp-images/3392/k-egg_jesko_100.jpg',
        'https://hips.hearstapps.com/hmg-prod/images/koenigsegg-jesko-106-1551799585.jpg',
        'https://hips.hearstapps.com/hmg-prod/images/koenigsegg-jesko-105-1551799593.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "482 km/h",
      engine: "5.0-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 22000,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Rimac C_Two",
      year: "2020",
      brand: "Rimac",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://assets.rimac-newsroom.com/1678873926-c_two_studio_front_01.jpg',
        'https://assets.newatlas.com/dims4/default/07b46cb/2147483647/strip/true/crop/1620x1080+0+0/resize/1620x1080!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2Farchive%2Frimac-c-two-electric-hypercar-2.jpg',
        'https://www.driving.co.uk/wp-content/uploads/sites/5/2018/03/Rimac-C-Two-rear-view-studio.jpg'],
      fuel: "Electric",
      seats: "Two Seaters",
      topSpeed: "415 km/h",
      engine: "Electric",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 20000,
      location: "Pretoria",
      category: "Sports"
    },
    {
      name: "Lotus Evija",
      year: "2021",
      brand: "Lotus",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://static.dezeen.com/uploads/2019/07/lotus-evija-car-design_dezeen_2364_col_2.jpg',
        'https://car-images.bauersecure.com/wp-images/3576/lotus_evija_055.jpg',
        'https://www.ehelix.com/wp-content/uploads/2019/07/3_Lotus_Evija_Rear-1.jpg'],
      fuel: "Electric",
      seats: "Two Seaters",
      topSpeed: "320 km/h",
      engine: "Electric",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 18000,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Hennessey Venom F5",
      year: "2020",
      brand: "Hennessey",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://news-site-za.s3.af-south-1.amazonaws.com/images/2020/12/Venom01.jpg',
        'https://www.automoblog.com/wp-content/uploads/2020/12/Hennessey-Venom-F5-3.jpg',
        'https://images.carexpert.com.au/resize/3000/-/app/uploads/2020/12/hennessey-venom-f5-crop-3.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "484 km/h",
      engine: "6.6-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 25000,
      location: "Pretoria",
      category: "Sports"
    },
    {
      name: "Rolls-Royce Wraith",
      year: "2019",
      brand: "Rolls-Royce",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://imagecdnsa.zigwheels.qa/large/gallery/exterior/31/362/rolls-royce-wraith-full-front-view.jpg',
        'https://www.motortrend.com/uploads/sites/11/2013/06/Rolls-Royce-Wraith-front-right-view.jpg',
        'https://prestigeandperformancecar.com/wp-content/uploads/RR_3079-1240x775.jpg'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "250 km/h",
      engine: "6.6-liter V12",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 8500,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Maserati GranTurismo",
      year: "2018",
      brand: "Maserati",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://platform.cstatic-images.com/in/v2/stock_photos/144d35cd-39cf-4d9a-b904-37dc476decc0/2482a2d5-ead8-4d20-b331-f6814550ca12.png',
        'https://s7g10.scene7.com/is/image/maserati/maserati/international/Models/default/2024/granturismo/modena/gt-modena_grigio-cangiante_cal-black_imola-diamond.png?$1920x2000$&fmt=png-alpha&fit=constrain',
        'https://images.collectingcars.com/005781/mark-foxDSC-1752.jpg?w=1263&fit=fillmax&crop=edges&auto=format,compress&cs=srgb&q=85'],
      fuel: "Petrol",
      seats: "Four Seaters",
      topSpeed: "301 km/h",
      engine: "4.7-liter V8",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 4200,
      location: "Pretoria",
      category: "Popular"
    },
    {
      name: "BMW i8",
      year: "2020",
      brand: "BMW",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://i.pinimg.com/originals/fd/7d/d3/fd7dd32a0039bbc87ff542ac6574b4a8.jpg',
        'https://assets.newatlas.com/dims4/default/639c85e/2147483647/strip/true/crop/3508x2339+0+145/resize/1200x800!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2Farchive%2Fbmw-i8-6.jpg',
        'https://cdn.bmwblog.com/wp-content/uploads/bmw-i8-official-images-201.jpg'],
      fuel: "Hybrid",
      seats: "Four Seaters",
      topSpeed: "250 km/h",
      engine: "1.5-liter I3 + Electric",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 4600,
      location: "Pretoria",
      category: "Recommended"
    },
    {
      name: "Lamborghini Huracan",
      year: "2021",
      brand: "Lamborghini",
      logo: "https://example.com/tesla-logo.png",
      images: ['https://www.motorbeam.com/wp-content/uploads/Lamborghini-Huracan-Wallpaper-1200x900.jpg',
        'https://360view.3dmodels.org/zoom/Lamborghini/Lamborghini_Huracan_LB724_Performante_2017_1000_0001.jpg',
        'https://www.topgear.com/sites/default/files/images/news-article/2020/01/5ea3b823a8085cde21eab2f4292c3d29/554573.jpg'],
      fuel: "Petrol",
      seats: "Two Seaters",
      topSpeed: "325 km/h",
      engine: "5.2-liter V10",
      transmission: "Automatic",
      airConditioning: "Yes",
      price: 7000,
      location: "Pretoria",
      category: "Sports"
    }
  ];

  try {
    for (const product of products) {
      const existingProduct = await Product.findOne({ name: product.name });
      if (existingProduct) {
        // Update the existing product
        await Product.updateOne({ name: product.name }, product);
        console.log(`Updated product: ${product.name}`);
      } else {
        // Insert the new product
        const newProduct = new Product(product);
        await newProduct.save();
        console.log(`Inserted product: ${product.name}`);
      }
    }
    mongoose.connection.close();
  } catch (err) {
    console.error('Error inserting or updating products:', err);
    mongoose.connection.close();
  }
})
.catch(err => {
  console.error('Error connecting to MongoDB:', err);
});